# Uncomment the next line to define a global platform for your project
platform :tvos, '18.0'

target 'nzbFlix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nzbFlix
  pod 'SDWebImage/Core'

  target 'nzbFlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nzbFlixUITests' do
    # Pods for testing
  end

end
